language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - echo "MAVEN_OPTS='-Xmx1536m'" > ~/.mavenrc
  - pushd mmd-schema/brainz-mmd2-jaxb
  - mvn -DskipTests install
  - popd
  - cd mb-solrquerywriter
