variables:
  majorVersion: '3.3.1'
  minorVersion: $[counter('minorVersion')]
  version: '$(majorVersion).$(minorVersion)'
  buildName: '$(Build.SourceBranchName).$(version)'
  imageName: 'lidarr/mb-solr'

trigger:
  branches:
    include:
    - master

pr:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- powershell: Write-Host "##vso[build.updatebuildnumber]$($env:VERSION)"
  displayName: Set Build Name
- checkout: self
  submodules: true
- task: Docker@2
  displayName: Build image
  inputs:
    containerRegistry: 'ghcr'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      latest
      $(Build.SourceBranchName)
      $(version)
